name: Publish Gem

on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Release Gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem build binance-connector-ruby.gemspec
          gem push *.gem
        env:
          RUBYGEMS_VERSION: "${{github.event.inputs.version}}"
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}