name: Ruby

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and rspec test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rubocop
        bundle exec rspec
